# Generated by Django 6.0.6 on 2026-06-08 04:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=200)),
                ('registration_number', models.CharField(db_index=True, help_text='Organization registration number (Trade License, RJSC, etc.)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail Store'), ('RESTAURANT', 'Restaurant'), ('SERVICE', 'Service Provider'), ('E_COMMERCE', 'E-commerce'), ('WHOLESALE', 'Wholesale'), ('OTHER', 'Other')], default='RETAIL', max_length=20)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=17)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_name'], name='merchants_busines_c6cdd8_idx'), models.Index(fields=['registration_number'], name='merchants_registr_cc86bc_idx'), models.Index(fields=['is_verified', 'is_active'], name='merchants_is_veri_cd92c8_idx'), models.Index(fields=['business_type'], name='merchants_busines_5993f8_idx')],
            },
        ),
    ]
